### ISSUE TITLE
New pypi release w/ post-1.3.0 changes?

### ISSUE THREAD

**Issue by bdeeney** [kennknowles/python-jsonpath-rw#23]
Would it be possible to cut a new pypi release that contains the latest changes present in master?  Specifically, we've encountered a bug that is fixed by #14 / fe2407bc.  Thanks for an excellent library!

**Comment by kennknowles** [comment]
I just uploaded version 1.4.0. Let me know if you have any trouble with it.

**Comment by bdeeney** [comment]
version 1.4.0 works great - thanks!
