### ISSUE TITLE
Does not Parse Strings Starting with Numbers

### ISSUE THREAD

**Issue by cbrady321** [kennknowles/python-jsonpath-rw#24]
It looks like the grammar does not accept alphanumeric keys starting with numerals, in my case UUIDs.  It's easy to reproduce:

    import uuid
    parse(u'$.a.{}.c'.format(uuid.uuid4()))

Unfortunately I am unfamiliar with yacc or I would have a go at fixing it.

**Comment by cbrady321** [comment]
OK, turns out I can read the lexer code without too much trouble.
Not sure why are IDs restricted to not starting with numbers. u'[a-zA-Z_@][a-zA-Z0-9_@\-]*'  We can extend numbers to exclude include alphanumerics using positive lookahead r'-?\d+(?=[terminator list])'.  Would doing this allow us to relax the definition of an ID? 

Thanks!

**Comment by kennknowles** [comment]
Hello! You can accomplish what you desire by enclosing your JSON field name in single or double quotes. Let me know if you hit a snag with that.

**Comment by cbrady321** [comment]
Thank you!  I did not notice that quotes would solve the problem.
I will likely force the uuids to start with a alpha char as I am also generating them.  This way the code beyond the uuid generator won't have to know what type of data it is handling.  
Is there a reason I shouldn't update the regex for ID?
