### ISSUE TITLE
An extra note in the doc

### ISSUE THREAD

**Issue by jric** [kennknowles/python-jsonpath-rw#26]
I'm not usually this slow, but I failed to notice from the examples in the documentation that you were operating on deserialized JSON python objects instead of JSON strings.  I came close to giving up before I realized my mistake.

I'd like to propose that you change this line in the README.md:

    # Extracting values is easy

to

    # Extracting values from deserialized JSON python objects is easy

**Comment by kennknowles** [comment]
You can extract from "any" python objects, sort of. Pull requests for the documentation are welcome :-)
