### ISSUE TITLE
Documentation does not show how to load JSon data from file or string

### ISSUE THREAD

**Issue by kevinroundy** [kennknowles/python-jsonpath-rw#44]
You are losing a lot of potential users, I expect (including me, so far), because the documentation does not contain examples of the most basic pre-requisite for using jsonpath-rw, which is how to parse JSon file or string data into Python objects that jsonpath-rw can act on. Thanks! --kevin

**Comment by jkmacc-LANL** [comment]
I agree that this should be at least in the README.  Would this do it?
```python
import json
d = json.loads('{"foo": [{"baz": 1}, {"baz": 2}]}')
# or
with open('myfile.json') as f:
    d = json.load(f)
```

**Comment by kevinroundy** [comment]
yes, thanks!
--kevin
